preload = ~/.config/hypr/wallpaper.png
preload = ~/.config/hypr/wallpaper2.png
preload = ~/.config/hypr/wallpaper3.png
wallpaper = DP-2, ~/.config/hypr/wallpaper2.png
wallpaper = HDMI-A-1, ~/.config/hypr/wallpaper3.png
wallpaper = DP-3, ~/.config/hypr/wallpaper.png
