windowrulev2 = suppressevent fullscreen, class:(flameshot), title:(flameshot)
windowrulev2 = rounding 0, class:(flameshot), title:(flameshot)
windowrulev2 = noborder, class:(flameshot), title:(flameshot)
windowrulev2 = monitor DP-3, class:(flameshot), title:(flameshot)
windowrulev2 = float, class:(flameshot), title:(flameshot)
windowrulev2 = fullscreenstate, class:(flameshot), title:(flameshot)
windowrulev2 = move 0 0, class:(flameshot), title:(flameshot)
windowrulev2 = stayfocused, class:(flameshot), title:(flameshot)
windowrulev2 = size 1920 1080, class:(flameshot), title:(flameshot)
windowrulev2 = float, class:(flameshot), title:(Upload image)
windowrulev2 = float, class:(flameshot), title:(Configuration)
windowrulev2 = float, class:(flameshot), title:(Capture Launcher)
windowrulev2 = float, class:(flameshot), title:(Save screenshot)

windowrulev2 = float, class:(Regalia)
windowrulev2 = center, class:(Regalia)
